services:
  php:
    image: php:latest
    stdin_open: true
    working_dir: /var/www/html
    volumes:
      - ./php:/var/www/html

  ruby:
    image: ruby:latest
    stdin_open: true
    working_dir: /usr/src/app
    volumes:
      - ./ruby:/usr/src/app